### ISSUE TITLE
discussions

### ISSUE THREAD

**Issue by vijayank88** [ufukyill/Issue-submit#1]
top_level has clock50MHz as clock signal
But you gave clock_signals as CLOCK_PORT? 
Is yosys synthesized properly?

CLOCK_PERIOD is 0.2ns is enough for this design? 

Clock configuration in openlane:

CLOCK_NET | The name of the Net input to root clock buffer used in Clock Tree Synthesis.
-- | --
CLOCK_PORT | The name of the design's clock port used in Static Timing Analysis.

**Comment by ufukyill** [comment]
At the beginning I changed clock port name as "clock50MHz " on config.tcl and faced same error hence i rechange it to default so posted version is default case.  In either case yosys phase was succesfull when i run interactively.

I have set CLOCK_PERIOD as `set ::env(CLOCK_PERIOD) "0.2"` in config. While i was testing design in modelsim everything was ok in waveform so i put together all modules in a .v file and started to openlane flow.

Apart of these, before starting openlane flow what are the parameters that i should set ? Is there any list of it or rule of thumb?

**Comment by vijayank88** [comment]
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/configuration/README.md
have detailed configuration variables. You can tweak other variables based on your design requirement

**Comment by vijayank88** [comment]
try this config.tcl
```
# User config
set ::env(DESIGN_NAME) top_level

# Change if needed
set ::env(VERILOG_FILES) [glob $::env(DESIGN_DIR)/src/*.v]

# Fill this
set ::env(CLOCK_PERIOD) "10.0"
set ::env(CLOCK_PORT) "clock50MHz"

set ::env(FP_CORE_UTIL) {30}

set ::env(PL_TARGET_DENSITY) {0.35}
set ::env(CELL_PAD) {1}

set filename $::env(DESIGN_DIR)/$::env(PDK)_$::env(STD_CELL_LIBRARY)_config.tcl
if { [file exists $filename] == 1} {
	source $filename
}
```

**Comment by ufukyill** [comment]
I tried your config and faced with an error: 
![image](https://user-images.githubusercontent.com/92793136/147825970-a0319af7-bc5a-405b-b69e-d9f9f1d20157.png)
Im facing with this error when i run flow non-interactively, too.

**Comment by vijayank88** [comment]
Maybe memory issue. How much RAM do you have?

I'm running the RTL what you shared, its in detail routing stage.

**Comment by ufukyill** [comment]
I have 16gb in my computer and sharing 8gb with virtual machine and 2 cores of CPU.

**Comment by ufukyill** [comment]
FYI who may need, I used config.tcl given below and increased vm ram to about 11gb end pass the placement. Thanks a lot to @vijayank88 for assistance .
config:
`
set ::env(DESIGN_NAME) top_level


set ::env(VERILOG_FILES) "$::env(DESIGN_DIR)/src/top_level.v"

set ::env(CLOCK_PERIOD) "10.0"
set ::env(CLOCK_PORT) "clock50MHz"
set ::env(FP_CORE_UTIL) {30}
set ::env(CELL_PAD) {1}
set ::env(PL_TARGET_DENSITY) {0.35}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {60}
set ::env(CLOCK_NET) $::env(CLOCK_PORT)


set filename $::env(DESIGN_DIR)/$::env(PDK)_$::env(STD_CELL_LIBRARY)_config.tcl
if { [file exists $filename] == 1} {
	source $filename
}
`
